#!/usr/bin/env node

const { copyFile, writeFile } = require('fs').promises;
const { join } = require('path');
const buildPage = require('./build-page');
const { availableLocales } = require('./locale');
const OsuWiki = require('./OsuWiki');
const printDiff = require('./print-diff');

if (process.argv.length !== 4) {
    console.error('Usage: build-status-pages <osu-wiki dir> <output dir>');
    process.exit(1);
}

const osuWiki = new OsuWiki(process.argv[2]);
const outputDirectory = process.argv[3];

(async () => {
    await osuWiki.pull();

    for (const locale of availableLocales) {
        await writeFile(
            join(outputDirectory, `${locale}.html`),
            await buildPage(osuWiki, locale),
        );

        const outdatedArticles = await osuWiki.getOutdatedTranslationArticlesForLocale(locale);

        for (const article of outdatedArticles) {
            const diff = await osuWiki.enDiffForArticle(article);
            const filename = osuWiki.enDiffLinkForArticle(article) + '.html';

            if (diff != null)
                printDiff(diff, join(outputDirectory, filename));
        }
    }

    await copyFile(
        join(__dirname, 'templates/style.css'),
        join(outputDirectory, 'style.css'),
    );
})();
